### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by bmhkim** [thomaslindstrom/color-picker#97] opened 2015-05-27 20:06 UTC
I'm getting this exception when I toggle any of the search options (weird!). Sometimes, when I'm viewing a file I haven't opened in a while, I can toggle options one or a few times without seeing this issue, but it eventually shows up.

    TypeError: undefined is not a function
        at ~/.atom/packages/color-picker/lib/ColorPicker-view.coffee:242:21
        at Object.Emitter.emit (~/.atom/packages/color-picker/lib/ColorPicker-view.coffee:6:9)
        at ~/.atom/packages/color-picker/lib/ColorPicker-view.coffee:206:14

This is occurring with all files, although regex search successfully toggles (i.e., successfully enables/disables).

Looks like this may (or may not) be related to bug https://github.com/thomaslindstrom/color-picker/issues/59. Edit: Upon further reading of bug 59, it looks like it very well may be related/the same..... (see the comment from ekonstantinidis)

OS X 10.10.3
Atom 0.201.0

User packages:
atom-ctags@3.2.0
atom-django@0.2.1
atom-jinja2@0.5.0
auto-detect-indentation@0.4.2
color-picker@2.0.1
dash@1.1.1
linter@0.12.6
linter-js-yaml@1.0.1
linter-jshint@0.1.5
linter-pylint@0.2.2
linter-shellcheck@0.0.8
linter-xmllint@0.0.6
merge-conflicts@1.3.1
minimap@4.9.0
monokai@0.14.0
peacock-syntax@1.4.0
save-session@0.15.3
seti-syntax@0.4.0
seti-ui@0.7.1
ssh-config@0.10.1
symbols-tree-view@0.9.3

**Comment by fbbdev** [comment] 2015-05-27 20:21
Affects me too!

**Comment by delucis** [comment] 2015-05-27 22:47
Same here.

1. Try switching search options

**Atom Version**: 0.201.0
**System**: Mac OS X 10.9.5
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v2.0.1


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/chris/.atom/packages/color-picker/lib/ColorPicker-view.coffee:209

TypeError: undefined is not a function
  at /Users/chris/.atom/packages/color-picker/lib/ColorPicker-view.coffee:209:56
  at Object.Emitter.emit (/Users/chris/.atom/packages/color-picker/lib/ColorPicker-view.coffee:172:31)
  at /Users/chris/.atom/packages/color-picker/lib/ColorPicker-view.coffee:185:65

```

### Commands

```
     -3:40.3.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  2x -3:40 core:backspace (atom-text-editor.editor.is-focused)
     -3:39.3.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -3:36.9.0 core:save (atom-text-editor.editor.is-focused)
  6x -3:26 core:undo (atom-text-editor.editor.is-focused)
     -3:21.2.0 core:save (atom-text-editor.editor.is-focused)
     -2:16.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:16.5.0 core:paste (atom-text-editor.editor.is-focused)
     -2:11 core:move-down (atom-text-editor.editor.is-focused)
     -2:09.8.0 core:undo (atom-text-editor.editor.is-focused)
     -2:08.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -1:19 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:19 core:cancel (atom-text-editor.editor.is-focused)
     -1:12.9.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
  3x -0:43.8.0 core:close (atom-text-editor.editor.is-focused)
     -0:03.1.0 find-and-replace:show (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.1
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by thomaslindstrom** [comment] 2015-05-28 00:31
This is really weird. I can't seem to be able to reproduce it. If anyone has time, would it be too much to ask for a simple video showing the bug? Anything to help me track this down will be greatly appreciated.

**Comment by bmhkim** [comment] 2015-05-28 00:38
Oddly enough, after restarting atom (not as a part of trying to debug this issue, it just happened at some point today), the issue went away for me.

**Comment by Tribex** [comment] 2015-05-28 00:40
Huh. I tried to reproduce it as well. Nothing. O-o

**Comment by delucis** [comment] 2015-05-28 00:41
Quick screengrab:
https://www.dropbox.com/s/cs44mhfjk6it0ug/colorpicker-error.mov?dl=0

But after reading @bmhkim’s comment, I restarted and similarly can no longer reproduce. Some kind of update error seems plausible.

**Comment by bmhkim** [comment] 2015-05-28 00:45
I can't speak to whether or not I saw this issue directly after updating, I didn't really pay attention to which plugins were updated today. However, I *can* say I agree it seems plausible, especially since it went away after restarting atom.

**Comment by thomaslindstrom** [comment] 2015-05-28 00:48
Thanks, @delucis. It's hard to say what this might be. I've still got my tabs on this error occurring because the *old* `color-picker` basically sucks and doesn't know how to clean itself up after being *“destroyed”*, and even after updating, is still running inside of Atom. Parallel to the new one.

If it disappears after restarting Atom, for all of you guys, I'm going to blatantly assume that is the case. 

Line 209, in `v2.0.0`, doesn't seem to be doing anything interesting, anyway. It's just a function definition:
```coffeescript
 emitClose: ->
```
https://github.com/thomaslindstrom/color-picker/blob/16b46256275a579f2f7fb2e01bf6c3cff860106d/lib/ColorPicker-view.coffee#L209

**Comment by thomaslindstrom** [comment] 2015-05-30 21:10
I'm going to close this for now. Please re-open this issue if the issue persists!

**Closed by thomaslindstrom** 2015-05-30 21:10 UTC
Labels: bug
