### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onColorChanged' of undefined

### ISSUE THREAD

**Issue by crperlin** [thomaslindstrom/color-picker#142] opened 2015-10-17 01:15 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v2.0.13

### Stack Trace

Uncaught TypeError: Cannot read property 'onColorChanged' of undefined

```
At /C:/Users/LinQunHe/.atom/packages/color-picker/lib/extensions/Arrow.coffee:66

TypeError: Cannot read property 'onColorChanged' of undefined
  at C:\Users\LinQunHe\.atom\packages\color-picker\lib\extensions\Arrow.coffee:64:22

```

### Commands

```
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "vim-mode"
    ],
    "themes": [
      "atom-dark-ui",
      "chester-atom-syntax"
    ],
    "disabledPackages": [
      "symbols-view",
      "minimap-find-and-replace",
      "minimap-pigments",
      "minimap"
    ]
  },
  "color-picker": {
    "abbreviateValues": true,
    "automaticReplace": true,
    "preferredFormat": "HEX",
    "triggerKey": "E"
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-ctags, v4.3.0
atom-html-preview, v0.1.11
atom-minify, v0.4.2
atom-shortcuts, v0.0.2
atom-ternjs, v0.8.3
autoclose-html, v0.19.0
autocomplete-html-entities, vundefined
autocomplete-paths, v1.0.2
bottom-dock, v0.3.5
chester-atom-syntax, v0.1.1
color-picker, v2.0.13
css-snippets, v0.9.0
docblockr, v0.7.3
emmet, v2.3.13
file-icons, v1.6.10
foldername-tabs, v0.1.5
fonts, v0.6.1
git-log, v0.4.1
gulp-manager, v0.2.10
gulp-snippets, v0.6.2
highlight-selected, v0.10.1
html-id-class-snippets, v1.4.1
javascript-snippets, v1.0.0
jquery-snippets, v11.0.0
jsformat, v0.9.0
linter, v1.8.1
linter-js-standard, v3.2.1
linter-jshint, vundefined
linter-less, v2.2.0
linter-manager, v0.2.3
open-recent, v2.3.0
pigments, v0.17.1
simplified-chinese-menu, v3.3.5
Sublime-Style-Column-Selection, v1.3.0
sync-settings, v0.6.0
todo-manager, v0.2.5
tree-view-git-status, v0.2.2
vim-mode, v0.61.0
vim-mode-visual-block, v0.2.13

# Dev
No dev packages
```

**Comment by thomaslindstrom** [comment] 2015-12-13 19:21
Duplicate of #114.

**Comment by thomaslindstrom** [comment] 2016-01-27 22:04
Please update `color-picker` to `v2.1.1` and **restart Atom**. This should be fixed now!

**Closed by thomaslindstrom** 2016-01-27 22:04 UTC
Labels: bug
