### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.

### ISSUE THREAD

**Issue by raulsmartin** [thomaslindstrom/color-picker#154] opened 2015-12-07 14:31 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v2.0.14

### Stack Trace

Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.

```
At /C:/Users/famil/.atom/packages/color-picker/lib/extensions/Alpha.coffee:93

Error: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.
    at Error (native)
    at Object._this.canvas.render (C:\Users\famil\.atom\packages\color-picker\lib\extensions\Alpha.coffee:103:35)
    at C:\Users\famil\.atom\packages\color-picker\lib\extensions\Alpha.coffee:112:29
    at Object.emit (C:\Users\famil\.atom\packages\color-picker\lib\modules\Emitter.coffee:11:23)
    at Object.emitColorChanged (C:\Users\famil\.atom\packages\color-picker\lib\extensions\Saturation.coffee:24:22)
    at C:\Users\famil\.atom\packages\color-picker\lib\extensions\Saturation.coffee:211:61
    at Object.emit (C:\Users\famil\.atom\packages\color-picker\lib\modules\Emitter.coffee:11:23)
    at Object.emitSelectionChanged (C:\Users\famil\.atom\packages\color-picker\lib\extensions\Saturation.coffee:18:22)
    at Object._this.control.setSelection (C:\Users\famil\.atom\packages\color-picker\lib\extensions\Saturation.coffee:200:43)
    at C:\Users\famil\.atom\packages\color-picker\lib\extensions\Saturation.coffee:208:30
```

### Commands

```
     -3:20.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -0:57 color-picker:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.14

# Dev
No dev packages
```

**Comment by thomaslindstrom** [comment] 2015-12-13 19:20
Duplicate of #114.

**Comment by thomaslindstrom** [comment] 2016-01-27 22:03
Please update `color-picker` to `v2.1.1` and **restart Atom**. This should be fixed now!

**Closed by thomaslindstrom** 2016-01-27 22:03 UTC
Labels: bug, duplicate
