### ISSUE TITLE
Does not open

### ISSUE THREAD

**Issue by AppIns** [thomaslindstrom/color-picker#155] opened 2015-12-11 00:39 UTC
The color picker does not open, uncaught error:

```
Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.

Error: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.
    at Error (native)
    at Object._this.canvas.render (C:\Users\orutw_000\.atom\packages\color-picker\lib\extensions\Alpha.coffee:103:35)
    at C:\Users\orutw_000\.atom\packages\color-picker\lib\extensions\Alpha.coffee:112:29
    at Object.emit (C:\Users\orutw_000\.atom\packages\color-picker\lib\modules\Emitter.coffee:11:23)
    at Object.emitColorChanged (C:\Users\orutw_000\.atom\packages\color-picker\lib\extensions\Saturation.coffee:24:22)
    at C:\Users\orutw_000\.atom\packages\color-picker\lib\extensions\Saturation.coffee:211:61
    at Object.emit (C:\Users\orutw_000\.atom\packages\color-picker\lib\modules\Emitter.coffee:11:23)
    at Object.emitSelectionChanged (C:\Users\orutw_000\.atom\packages\color-picker\lib\extensions\Saturation.coffee:18:22)
    at Object._this.control.setSelection (C:\Users\orutw_000\.atom\packages\color-picker\lib\extensions\Saturation.coffee:200:43)
    at C:\Users\orutw_000\.atom\packages\color-picker\lib\extensions\Saturation.coffee:208:30
    at Object.emit (C:\Users\orutw_000\.atom\packages\color-picker\lib\modules\Emitter.coffee:11:23)
    at Object.emitInputColor (file:///C:/Users/orutw_000/.atom/packages/color-picker/lib/ColorPicker-view.coffee:233:22)
    at Object.open (file:///C:/Users/orutw_000/.atom/packages/color-picker/lib/ColorPicker-view.coffee:340:18)
    at atom-text-editor.<anonymous> (C:\Users\orutw_000\.atom\packages\color-picker\lib\ColorPicker.coffee:42:68)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\orutw_000\AppData\Local\atom\app-1.3.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\orutw_000\AppData\Local\atom\app-1.3.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\orutw_000\AppData\Local\atom\app-1.3.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\orutw_000\AppData\Local\atom\app-1.3.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\orutw_000\AppData\Local\atom\app-1.3.0\resources\app.asar\src\window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (C:\Users\orutw_000\AppData\Local\atom\app-1.3.0\resources\app.asar\src\window-event-handler.js:3:61)
```

**Comment by thomaslindstrom** [comment] 2015-12-13 19:20
Duplicate of #114.

**Closed** 2015-12-20 02:13 UTC
Labels: bug, duplicate
